// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const addIncident = `-- name: AddIncident :one
INSERT INTO incidents (latitude, longitude)
    VALUES ($1, $2)
RETURNING
    id, latitude, longitude
`

type AddIncidentParams struct {
	Latitude  string
	Longitude string
}

func (q *Queries) AddIncident(ctx context.Context, arg AddIncidentParams) (Incident, error) {
	row := q.db.QueryRowContext(ctx, addIncident, arg.Latitude, arg.Longitude)
	var i Incident
	err := row.Scan(&i.ID, &i.Latitude, &i.Longitude)
	return i, err
}

const deleteIncidentByID = `-- name: DeleteIncidentByID :one
DELETE FROM incidents
WHERE id = $1
RETURNING
    id, latitude, longitude
`

func (q *Queries) DeleteIncidentByID(ctx context.Context, id int64) (Incident, error) {
	row := q.db.QueryRowContext(ctx, deleteIncidentByID, id)
	var i Incident
	err := row.Scan(&i.ID, &i.Latitude, &i.Longitude)
	return i, err
}

const getAllIncidents = `-- name: GetAllIncidents :many
SELECT
    id, latitude, longitude
FROM
    incidents
`

func (q *Queries) GetAllIncidents(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.QueryContext(ctx, getAllIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(&i.ID, &i.Latitude, &i.Longitude); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncidentByID = `-- name: GetIncidentByID :one
SELECT
    id, latitude, longitude
FROM
    incidents
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetIncidentByID(ctx context.Context, id int64) (Incident, error) {
	row := q.db.QueryRowContext(ctx, getIncidentByID, id)
	var i Incident
	err := row.Scan(&i.ID, &i.Latitude, &i.Longitude)
	return i, err
}
